# Generated by Django 6.0.1 on 2026-01-31 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=10)),
                ('position', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right')], max_length=5)),
                ('duration', models.IntegerField()),
                ('left_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_child', to='routes.airportroute')),
                ('right_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_child', to='routes.airportroute')),
            ],
        ),
    ]
