# Generated by Django 6.0.1 on 2026-01-31 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_airportroute_parent_airport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airportroute',
            options={'verbose_name': 'Airport Route', 'verbose_name_plural': 'Airport Routes'},
        ),
        migrations.AlterUniqueTogether(
            name='airportroute',
            unique_together={('parent_airport', 'position')},
        ),
        migrations.AlterField(
            model_name='airportroute',
            name='airport_code',
            field=models.CharField(help_text='Airport identifier (e.g., Airport A, Airport B)', max_length=100),
        ),
        migrations.AlterField(
            model_name='airportroute',
            name='duration',
            field=models.IntegerField(default=0, help_text='Flight duration from parent airport (in minutes)'),
        ),
        migrations.AlterField(
            model_name='airportroute',
            name='parent_airport',
            field=models.ForeignKey(blank=True, help_text='Parent airport in the tree structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='routes.airportroute'),
        ),
        migrations.AlterField(
            model_name='airportroute',
            name='position',
            field=models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Root', 'Root')], help_text='Position relative to parent airport', max_length=10),
        ),
        migrations.RemoveField(
            model_name='airportroute',
            name='left_node',
        ),
        migrations.RemoveField(
            model_name='airportroute',
            name='right_node',
        ),
    ]
